# Generated by Django 5.2.12 on 2026-06-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('organisation', models.CharField(max_length=200)),
                ('system_type', models.CharField(blank=True, choices=[('', 'Select a system to digitalize'), ('emr', 'Electronic Medical Records (EMR)'), ('drugs', 'Drugs & Consumables Management'), ('hie', 'Health Information Exchange (HIE)'), ('academic', 'Academic / Training Management System'), ('dms', 'Document Management System'), ('hrms', 'Human Resources Management'), ('inventory', 'Inventory Management'), ('erp', 'Enterprise Resource Planning'), ('custom', 'Custom Solution')], max_length=100)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
