# Generated by Django 5.2.12 on 2026-06-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='system_type',
            field=models.CharField(blank=True, choices=[('', 'Select a system to digitalize'), ('custom', 'Custom Solution'), ('emr', 'Electronic Medical Records (EMR)'), ('drugs', 'Drugs & Consumables Management'), ('hie', 'Health Information Exchange (HIE)'), ('academic', 'Academic / Training Management System'), ('dms', 'Document Management System'), ('hrms', 'Human Resources Management'), ('inventory', 'Inventory Management'), ('erp', 'Enterprise Resource Planning')], max_length=100),
        ),
    ]
